version: '3.8'

x-settings: &global
  environment:
    - ALLOWED_HOSTS="*"
    - SECRET_KEY='django-insecure-j)rc7@f%y3dn1(+v0*@c-*zov6&af(3b315*qj8y^ujt%mv7ux'
    - DEBUG=False
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_HOST=database
    - DB_PORT=5432
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0


services:
  nginx:
    image: nginx:1.21.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./static:/var/www/look/static
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    container_name: api
    command: gunicorn look_saver.wsgi:application --bind 0.0.0.0:8080
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
    ports:
      - "8080:8080"
    <<: *global
    depends_on:
      - database

  database:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *global

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always


  celery:
    restart: always
    build:
      context: .
    volumes:
      - ./static:/app/static
    command: celery -A look_saver worker -l INFO
    <<: *global
    depends_on:
      - database
      - redis
      - api

volumes:
  postgres_data:
  redis-data: