# Generated by Django 4.0.2 on 2022-02-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='accessory_media')),
            ],
            options={
                'db_table': 'accessory',
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('pants_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pants_media')),
            ],
            options={
                'db_table': 'pants',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('shoes_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='shoes_media')),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('top_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='top_media')),
            ],
            options={
                'db_table': 'top',
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('look_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look', to='api.accessory')),
                ('pants_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look', to='api.pants')),
                ('shoes_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look', to='api.shoes')),
                ('top_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look', to='api.top')),
            ],
            options={
                'db_table': 'look',
            },
        ),
    ]
