# Generated by Django 4.0.2 on 2022-02-17 11:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="look",
            old_name="user_id",
            new_name="owner",
        ),
    ]
