# Generated by Django 4.0.2 on 2022-02-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutfitItems',
            new_name='OutfitItem',
        ),
    ]
