# Generated by Django 4.0.2 on 2022-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outfititem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
