# Generated by Django 4.0.2 on 2022-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
